server:
  port: 8081
spring:
  rabbitmq:
    host: 47.107.225.73
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: leyou.item.exchange
    publisher-confirms: true
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?useSSL=false&useUnicode=true&characterEncoding=UTF-8

    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

logging:
    level:
      com.leyou.item.mapper: debug
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

